name: Publish Chrome Extension

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/*.yml"
      - "src/*"
    jobs:
      publish:
        name: Publish
        runs-on: ubuntu-latest
        strategy:
          matrix:
            mongodb-version: [4.0]
            steps:
              - uses: actions/checkout@v2
              - uses: actions/setup-node@v1
                with:
                  node-version: "12.x"
                  registry-url: "https://registry.npmjs.org"

              - name: Get yarn cache directory path
                id: yarn-cache-dir-path
                run: echo "::set-output name=dir::$(yarn cache dir)"

              - name: Get yarn cache directory path
                id: yarn-cache-dir-path
                run: echo "::set-output name=dir::$(yarn cache dir)"

              - uses: actions/cache@v2
                id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
                with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                    ${{ runner.os }}-yarn-

              - name: Install
                run: yarn install --frozen-lockfile

              - name: Build
                run: yarn build

              - name: Upload Extension
                uses: Klemensas/chrome-extension-upload-action@$VERSION
                with:
                  refresh-token: ${{ secrets.REFRESH_TOKEN }}
                  client-id: ${{ secrets.CLIENT_ID }}
                  client-secret: ${{ secrets.CLIENT_SECRET }}
                  file-name: './extension.zip'
                  app-id: ${{ secrets.APP_ID }}
                  publish: true
